# Use an official Nginx runtime as a parent image
FROM nginx:alpine

# Remove default configuration and add custom
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# Copy static files to serve
COPY templates /usr/share/nginx/html

# Expose port 80 for the web server
EXPOSE 80
